# Chaper 4 - Loops

#### while: warming up
<pre>
The while loop is like a repeated if statement. The code is executed over and over again, as long as the condition is True. Have another look at its recipe.

while condition :
    expression
Can you tell how many printouts the following while loop will do?

x = 1
while x < 4 :
    print(x)
    x = x + 1
</pre>

<pre>

<b>Instructions:</b>
Possible Answers:
1.  0
2.  1
3.  3 [Correct Answer]
4.  4
</pre>

#### Basic while loop
<pre>
Below you can find the example from the video where the error variable, initially equal to 50.0, is divided by 4 and printed out on every run:

error = 50.0
while error > 1 :
    error = error / 4
    print(error)
    
This example will come in handy, because it's time to build a while loop yourself! We're going to code a while loop that implements a very basic control system for a inverted pendulum. If there's an offset from standing perfectly straight, the while loop will incrementally fix this offset.

</pre>

<pre>

<b>Instructions:</b>
- Create the variable offset with an initial value of 8.
- Code a while loop that keeps running as long as offset is not equal to 0. Inside the while loop:
- Print out the sentence "correcting...".
- Next, decrease the value of offset by 1. You can do this with 
        offset = offset - 1.
- Finally, print out offset so you can see how it changes.

</pre>

In [1]:
# Initialize offset
offset = 8

# Code the while loop
while offset != 0:
    print("Correcting...")
    offset = offset - 1
    print(offset)

Correcting...
7
Correcting...
6
Correcting...
5
Correcting...
4
Correcting...
3
Correcting...
2
Correcting...
1
Correcting...
0


<hr>

#### Add Conditionals
<pre>
Add conditionals
The while loop that corrects the offset is a good start, but what if offset is negative? You can try to run the sample code on the right where offset is initialized to -6, but your sessions will be disconnected. The while loop will never stop running, because offset will be further decreased on every run. offset != 0 will never become False and the while loop continues forever.

Fix things by putting an if-else statement inside the while loop.
</pre>

<pre>

<b>INSTRUCTIONS</b>
- Inside the while loop, replace offset = offset - 1 by an if-else statement:
- If offset > 0, you should decrease offset by 1.
- Else, you should increase offset by 1.
- If you've coded things correctly, hitting Submit Answer should work this time.
</pre>

<pre>
<b>Problem:</b>
# Initialize offset
offset = -6

# Code the while loop
while offset != 0 :
    print("correcting...")
    offset = offset - 1
    print(offset)
</pre>

In [2]:
# Initialize offset
offset = -6

# Code the while loop
while offset != 0 :
    print("correcting...")
    if offset > 0:
        offset = offset - 1
    else:
        offset = offset + 1
    print(offset)    

correcting...
-5
correcting...
-4
correcting...
-3
correcting...
-2
correcting...
-1
correcting...
0


<hr>

#### Loop over a list
<pre>
Have another look at the for loop that Filip showed in the video:

fam = [1.73, 1.68, 1.71, 1.89]
for height in fam : 
    print(height)

As usual, you simply have to indent the code with 4 spaces to tell Python which code should be executed in the for loop.

The areas variable, containing the area of different rooms in your house, is already defined.


<b>INSTRUCTIONS</b>
Write a for loop that iterates over all elements of the areas list and prints out every element separately.

<b>Problem:</b>
   # areas list
   areas = [11.25, 18.0, 20.0, 10.75, 9.50]
   
   # Code the for loop
</pre>

In [3]:
# areas list
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Code the for loop
for a in areas:
    print(a)

11.25
18.0
20.0
10.75
9.5


<hr>

### Indexes and values (1)
<pre>
Using a for loop to iterate over a list only gives you access to every list element in each run, one after the other. If you also want to access the index information, so where the list element you're iterating over is located, you can use enumerate().

As an example, have a look at how the for loop from the video was converted:

fam = [1.73, 1.68, 1.71, 1.89]
for index, height in enumerate(fam) :
    print("index " + str(index) + ": " + str(height))


<b>INSTRUCTIONS</b>
Adapt the for loop in the sample code to use enumerate(). On each run, a line of the form "room x: y" should be printed, where x is the index of the list element and y is the actual list element, i.e. the area. Make sure to print out this exact string, with the correct spacing.

<b>Problem:</b>
   # areas list
   areas = [11.25, 18.0, 20.0, 10.75, 9.50]
   
   # Change for loop to use enumerate()
   for a in areas :
       print(a)
</pre>

In [4]:
# areas list
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Change for loop to use enumerate()
for index, a in enumerate(areas):
    print("room " + str(index) + ": " + str(a))

room 0: 11.25
room 1: 18.0
room 2: 20.0
room 3: 10.75
room 4: 9.5


<hr>

#### Indexes and values (2)
<pre>
For non-programmer folks, room 0: 11.25 is strange. Wouldn't it be better if the count started at 1?

<b>INSTRUCTIONS</b>
Adapt the print() function in the for loop on the right so that the first printout becomes "room 1: 11.25", the second one "room 2: 18.0" and so on.


<b>Problem:</b>
    # areas list
    areas = [11.25, 18.0, 20.0, 10.75, 9.50]
    
    # Code the for loop
    for index, area in enumerate(areas) :
        print("room " + str(index) + ": " + str(area))
    
</pre>

In [5]:
# areas list
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Code the for loop
for index, area in enumerate(areas) :
    print("room " + str(index+1) + ": " + str(area))

room 1: 11.25
room 2: 18.0
room 3: 20.0
room 4: 10.75
room 5: 9.5


<hr>

#### Loop over list of lists
<pre>
Remember the house variable from the Intro to Python course? Have a look at its definition on the right. It's basically a list of lists, where each sublist contains the name and area of a room in your house.

It's up to you to build a for loop from scratch this time!


<b>INSTRUCTIONS</b>
Write a for loop that goes through each sublist of house and prints out the x is y sqm, where x is the name of the room and y is the area of the room.

<b>Problem:</b>
    # house list of lists
    house = [["hallway", 11.25], 
             ["kitchen", 18.0], 
             ["living room", 20.0], 
             ["bedroom", 10.75], 
             ["bathroom", 9.50]]
             
    # Build a for loop from scratch
    
</pre>